// <auto-generated />
using System;
using CourseWork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseWork.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513105852_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseWork.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 250.00m,
                            Email = "shevchenko.o@gmail.com",
                            FullName = "Шевченко Олександр Петрович",
                            Phone = "+380501234567"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 180.50m,
                            Email = "kovalenko.m@ukr.net",
                            FullName = "Коваленко Марія Іванівна",
                            Phone = "+380672345678"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 320.00m,
                            Email = "bondarenko.a@gmail.com",
                            FullName = "Бондаренко Андрій Сергійович",
                            Phone = "+380933456789"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 95.75m,
                            Email = "tkachenko.o@ukr.net",
                            FullName = "Ткаченко Ольга Вікторівна",
                            Phone = "+380504567890"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 410.00m,
                            Email = "melnyk.d@gmail.com",
                            FullName = "Мельник Дмитро Олегович",
                            Phone = "+380675678901"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 150.25m,
                            Email = "kravchenko.n@ukr.net",
                            FullName = "Кравченко Наталія Юріївна",
                            Phone = "+380936789012"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 200.00m,
                            Email = "oliinyk.i@gmail.com",
                            FullName = "Олійник Ігор Васильович",
                            Phone = "+380507890123"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 75.00m,
                            Email = "polishchuk.k@ukr.net",
                            FullName = "Поліщук Катерина Андріївна",
                            Phone = "+380678901234"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 560.00m,
                            Email = "savchenko.v@gmail.com",
                            FullName = "Савченко Віталій Миколайович",
                            Phone = "+380939012345"
                        },
                        new
                        {
                            Id = 10,
                            Balance = 300.00m,
                            Email = "rudenko.a@ukr.net",
                            FullName = "Руденко Анна Олександрівна",
                            Phone = "+380500123456"
                        },
                        new
                        {
                            Id = 11,
                            Balance = 125.50m,
                            Email = "lytvynenko.s@gmail.com",
                            FullName = "Литвиненко Сергій Ігорович",
                            Phone = "+380671234509"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 440.00m,
                            Email = "moroz.y@ukr.net",
                            FullName = "Мороз Юлія Дмитрівна",
                            Phone = "+380932345610"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 88.00m,
                            Email = "pavlenko.r@gmail.com",
                            FullName = "Павленко Роман Тарасович",
                            Phone = "+380503456711"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 670.00m,
                            Email = "khomenko.i@ukr.net",
                            FullName = "Хоменко Ірина Степанівна",
                            Phone = "+380674567812"
                        },
                        new
                        {
                            Id = 15,
                            Balance = 215.00m,
                            Email = "honcharenko.m@gmail.com",
                            FullName = "Гончаренко Максим Павлович",
                            Phone = "+380935678913"
                        });
                });

            modelBuilder.Entity("CourseWork.Models.GeoZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("SpeedLimit")
                        .HasColumnType("double precision");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("GeoZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.05 49.44, 32.07 49.44, 32.07 49.45, 32.05 49.45, 32.05 49.44))"),
                            Description = "Центральна зона міста Черкаси",
                            Name = "Центр Черкас",
                            SpeedLimit = 25.0,
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 2,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.045 49.448, 32.055 49.448, 32.055 49.456, 32.045 49.456, 32.045 49.448))"),
                            Description = "Зона пішохідної набережної",
                            Name = "Набережна зона",
                            SpeedLimit = 10.0,
                            ZoneType = "SpeedLimited"
                        },
                        new
                        {
                            Id = 3,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.048 49.434, 32.058 49.434, 32.058 49.442, 32.048 49.442, 32.048 49.434))"),
                            Description = "Паркова зона зі зниженою швидкістю",
                            Name = "Парк 30-річчя Перемоги",
                            SpeedLimit = 15.0,
                            ZoneType = "SpeedLimited"
                        },
                        new
                        {
                            Id = 4,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.005 49.42, 32.025 49.42, 32.025 49.432, 32.005 49.432, 32.005 49.42))"),
                            Description = "Житловий район Митниця",
                            Name = "Митниця",
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 5,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.08 49.425, 32.1 49.425, 32.1 49.44, 32.08 49.44, 32.08 49.425))"),
                            Description = "Промислова зона — рух заборонено",
                            Name = "Промзона Черкаси",
                            ZoneType = "Restricted"
                        },
                        new
                        {
                            Id = 6,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.025 49.412, 32.045 49.412, 32.045 49.424, 32.025 49.424, 32.025 49.412))"),
                            Description = "Район Соснівка",
                            Name = "Соснівка",
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 7,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.07 49.424, 32.09 49.424, 32.09 49.436, 32.07 49.436, 32.07 49.424))"),
                            Description = "Район Дахнівка",
                            Name = "Дахнівка",
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 8,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.056 49.438, 32.06 49.438, 32.06 49.442, 32.056 49.442, 32.056 49.438))"),
                            Description = "Зона паркування біля ТРЦ",
                            Name = "Паркінг ТРЦ Любава",
                            SpeedLimit = 5.0,
                            ZoneType = "Parking"
                        },
                        new
                        {
                            Id = 9,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.064 49.432, 32.072 49.432, 32.072 49.438, 32.064 49.438, 32.064 49.432))"),
                            Description = "Зона біля залізничного вокзалу",
                            Name = "Вокзальна площа",
                            SpeedLimit = 10.0,
                            ZoneType = "SpeedLimited"
                        },
                        new
                        {
                            Id = 10,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((32.052 49.444, 32.06 49.444, 32.06 49.45, 32.052 49.45, 32.052 49.444))"),
                            Description = "Вулиця Хрещатик та прилеглі квартали",
                            Name = "Хрещатик Черкаси",
                            SpeedLimit = 20.0,
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 11,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((31.455 49.748, 31.47 49.748, 31.47 49.758, 31.455 49.758, 31.455 49.748))"),
                            Description = "Центральна частина міста Канів",
                            Name = "Канів Центр",
                            SpeedLimit = 25.0,
                            ZoneType = "Allowed"
                        },
                        new
                        {
                            Id = 12,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((31.465 49.752, 31.478 49.752, 31.478 49.76, 31.465 49.76, 31.465 49.752))"),
                            Description = "Заповідна зона Тарасової гори",
                            Name = "Тарасова гора",
                            SpeedLimit = 10.0,
                            ZoneType = "SpeedLimited"
                        },
                        new
                        {
                            Id = 13,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((31.45 49.744, 31.462 49.744, 31.462 49.752, 31.45 49.752, 31.45 49.744))"),
                            Description = "Набережна зона Канева",
                            Name = "Набережна Канева",
                            SpeedLimit = 15.0,
                            ZoneType = "SpeedLimited"
                        },
                        new
                        {
                            Id = 14,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((31.454 49.747, 31.462 49.747, 31.462 49.753, 31.454 49.753, 31.454 49.747))"),
                            Description = "Зона паркування в парку Канева",
                            Name = "Парк відпочинку Канів",
                            SpeedLimit = 5.0,
                            ZoneType = "Parking"
                        },
                        new
                        {
                            Id = 15,
                            Boundary = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((31.475 49.74, 31.49 49.74, 31.49 49.75, 31.475 49.75, 31.475 49.74))"),
                            Description = "Промислова зона Канева — рух заборонено",
                            Name = "Промзона Канів",
                            ZoneType = "Restricted"
                        });
                });

            modelBuilder.Entity("CourseWork.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("EndRentalPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StartRentalPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EndRentalPointId");

                    b.HasIndex("StartRentalPointId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EndRentalPointId = 2,
                            EndTime = new DateTime(2026, 5, 1, 9, 25, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 1,
                            StartTime = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 127.50m,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            EndRentalPointId = 5,
                            EndTime = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 2,
                            StartTime = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            TotalCost = 170.00m,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            EndRentalPointId = 1,
                            EndTime = new DateTime(2026, 5, 2, 14, 40, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 3,
                            StartTime = new DateTime(2026, 5, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 130.00m,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            EndRentalPointId = 4,
                            EndTime = new DateTime(2026, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 7,
                            StartTime = new DateTime(2026, 5, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 158.00m,
                            VehicleId = 7
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            EndRentalPointId = 3,
                            EndTime = new DateTime(2026, 5, 3, 8, 35, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 1,
                            StartTime = new DateTime(2026, 5, 3, 8, 15, 0, 0, DateTimeKind.Utc),
                            TotalCost = 80.00m,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            EndRentalPointId = 6,
                            EndTime = new DateTime(2026, 5, 3, 11, 45, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 2,
                            StartTime = new DateTime(2026, 5, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 183.00m,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            EndRentalPointId = 9,
                            EndTime = new DateTime(2026, 5, 4, 8, 30, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 4,
                            StartTime = new DateTime(2026, 5, 4, 7, 30, 0, 0, DateTimeKind.Utc),
                            TotalCost = 125.00m,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            EndRentalPointId = 7,
                            EndTime = new DateTime(2026, 5, 4, 13, 20, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 5,
                            StartTime = new DateTime(2026, 5, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 95.00m,
                            VehicleId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            EndRentalPointId = 10,
                            EndTime = new DateTime(2026, 5, 5, 9, 50, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 7,
                            StartTime = new DateTime(2026, 5, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 293.00m,
                            VehicleId = 10
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            EndRentalPointId = 8,
                            EndTime = new DateTime(2026, 5, 5, 15, 30, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 6,
                            StartTime = new DateTime(2026, 5, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 132.00m,
                            VehicleId = 9
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 11,
                            EndRentalPointId = 13,
                            EndTime = new DateTime(2026, 5, 6, 10, 55, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 11,
                            StartTime = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 127.00m,
                            VehicleId = 11
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 12,
                            EndRentalPointId = 12,
                            EndTime = new DateTime(2026, 5, 6, 12, 15, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 11,
                            StartTime = new DateTime(2026, 5, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 88.00m,
                            VehicleId = 12
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 13,
                            EndRentalPointId = 14,
                            EndTime = new DateTime(2026, 5, 7, 17, 35, 0, 0, DateTimeKind.Utc),
                            StartRentalPointId = 13,
                            StartTime = new DateTime(2026, 5, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            TotalCost = 235.00m,
                            VehicleId = 14
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 14,
                            StartRentalPointId = 12,
                            StartTime = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            VehicleId = 13
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 15,
                            StartRentalPointId = 14,
                            StartTime = new DateTime(2026, 5, 8, 9, 30, 0, 0, DateTimeKind.Utc),
                            VehicleId = 15
                        });
                });

            modelBuilder.Entity("CourseWork.Models.RentalPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RentalPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "м. Черкаси, бул. Шевченка, 205",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.0621 49.4445)"),
                            Name = "Центр Черкаси"
                        },
                        new
                        {
                            Id = 2,
                            Address = "м. Черкаси, вул. Благовісна, 170",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.053 49.438)"),
                            Name = "Парк ім. 30-річчя Перемоги"
                        },
                        new
                        {
                            Id = 3,
                            Address = "м. Черкаси, вул. Набережна, 1",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.049 49.452)"),
                            Name = "Набережна Дніпра"
                        },
                        new
                        {
                            Id = 4,
                            Address = "м. Черкаси, вул. Героїв Дніпра, 45",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.015 49.426)"),
                            Name = "Район Митниця"
                        },
                        new
                        {
                            Id = 5,
                            Address = "м. Черкаси, вул. Смілянська, 36",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.058 49.44)"),
                            Name = "ТРЦ Любава"
                        },
                        new
                        {
                            Id = 6,
                            Address = "м. Черкаси, вул. Вокзальна, 1",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.068 49.435)"),
                            Name = "Вокзал Черкаси"
                        },
                        new
                        {
                            Id = 7,
                            Address = "м. Черкаси, вул. Хрещатик, 190",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.055 49.447)"),
                            Name = "Парк Перемоги"
                        },
                        new
                        {
                            Id = 8,
                            Address = "м. Черкаси, вул. Дахнівська, 12",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.08 49.43)"),
                            Name = "Дахнівка"
                        },
                        new
                        {
                            Id = 9,
                            Address = "м. Черкаси, вул. Сумгаїтська, 28",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.034 49.418)"),
                            Name = "Район Соснівка"
                        },
                        new
                        {
                            Id = 10,
                            Address = "м. Черкаси, пл. Б. Хмельницького, 1",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.06 49.446)"),
                            Name = "Площа Богдана Хмельницького"
                        },
                        new
                        {
                            Id = 11,
                            Address = "м. Канів, вул. Шевченка, 89",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.461 49.752)"),
                            Name = "Канів Центр"
                        },
                        new
                        {
                            Id = 12,
                            Address = "м. Канів, Тарасова гора, 1",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.47 49.755)"),
                            Name = "Тарасова гора"
                        },
                        new
                        {
                            Id = 13,
                            Address = "м. Канів, вул. Набережна, 5",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.456 49.748)"),
                            Name = "Набережна Канева"
                        },
                        new
                        {
                            Id = 14,
                            Address = "м. Канів, вул. Героїв, 34",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.458 49.75)"),
                            Name = "Парк Канів"
                        },
                        new
                        {
                            Id = 15,
                            Address = "м. Канів, вул. Київська, 70",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.463 49.754)"),
                            Name = "Автостанція Канів"
                        });
                });

            modelBuilder.Entity("CourseWork.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer");

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("RentalPointId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RentalPointId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 95,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.0621 49.4445)"),
                            IsAvailable = true,
                            RentalPointId = 1,
                            SerialNumber = "XM-PRO2-0001",
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BatteryLevel = 80,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.0623 49.4446)"),
                            IsAvailable = true,
                            RentalPointId = 1,
                            SerialNumber = "XM-ESS-0002",
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            BatteryLevel = 60,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.05 49.44)"),
                            IsAvailable = false,
                            SerialNumber = "NB-MAX-0003",
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            BatteryLevel = 100,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.053 49.438)"),
                            IsAvailable = true,
                            RentalPointId = 2,
                            SerialNumber = "KG-S3P-0004",
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            BatteryLevel = 45,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.049 49.452)"),
                            IsAvailable = true,
                            RentalPointId = 3,
                            SerialNumber = "SG-E2-0005",
                            VehicleTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            BatteryLevel = 100,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.015 49.426)"),
                            IsAvailable = true,
                            RentalPointId = 4,
                            SerialNumber = "VL-CLS-0006",
                            VehicleTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            BatteryLevel = 100,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.056 49.4475)"),
                            IsAvailable = false,
                            SerialNumber = "VL-TRL-0007",
                            VehicleTypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            BatteryLevel = 70,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.058 49.44)"),
                            IsAvailable = true,
                            RentalPointId = 5,
                            SerialNumber = "EV-CTE-0008",
                            VehicleTypeId = 8
                        },
                        new
                        {
                            Id = 9,
                            BatteryLevel = 88,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.068 49.435)"),
                            IsAvailable = true,
                            RentalPointId = 6,
                            SerialNumber = "XM-1S-0009",
                            VehicleTypeId = 9
                        },
                        new
                        {
                            Id = 10,
                            BatteryLevel = 55,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (32.055 49.447)"),
                            IsAvailable = true,
                            RentalPointId = 7,
                            SerialNumber = "KG-M4-0010",
                            VehicleTypeId = 10
                        },
                        new
                        {
                            Id = 11,
                            BatteryLevel = 100,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.461 49.752)"),
                            IsAvailable = true,
                            RentalPointId = 11,
                            SerialNumber = "VL-FLD-0011",
                            VehicleTypeId = 11
                        },
                        new
                        {
                            Id = 12,
                            BatteryLevel = 30,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.465 49.751)"),
                            IsAvailable = false,
                            SerialNumber = "NB-F40-0012",
                            VehicleTypeId = 12
                        },
                        new
                        {
                            Id = 13,
                            BatteryLevel = 90,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.47 49.755)"),
                            IsAvailable = true,
                            RentalPointId = 12,
                            SerialNumber = "EV-CRG-0013",
                            VehicleTypeId = 13
                        },
                        new
                        {
                            Id = 14,
                            BatteryLevel = 75,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.456 49.748)"),
                            IsAvailable = true,
                            RentalPointId = 13,
                            SerialNumber = "SG-P65-0014",
                            VehicleTypeId = 14
                        },
                        new
                        {
                            Id = 15,
                            BatteryLevel = 20,
                            CurrentLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (31.458 49.75)"),
                            IsAvailable = true,
                            RentalPointId = 14,
                            SerialNumber = "KG-GBS-0015",
                            VehicleTypeId = 15
                        });
                });

            modelBuilder.Entity("CourseWork.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PerMinuteRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnlockFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xiaomi Mi Pro 2",
                            PerMinuteRate = 4.50m,
                            UnlockFee = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xiaomi Mi Essential",
                            PerMinuteRate = 3.50m,
                            UnlockFee = 10.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ninebot Max G30",
                            PerMinuteRate = 5.00m,
                            UnlockFee = 20.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kugoo S3 Pro",
                            PerMinuteRate = 3.80m,
                            UnlockFee = 12.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Segway Ninebot E2",
                            PerMinuteRate = 3.00m,
                            UnlockFee = 10.00m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Велосипед міський Classic",
                            PerMinuteRate = 2.00m,
                            UnlockFee = 5.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Велосипед гірський Trail",
                            PerMinuteRate = 2.50m,
                            UnlockFee = 8.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Електровелосипед City-E",
                            PerMinuteRate = 4.00m,
                            UnlockFee = 15.00m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Xiaomi Mi 1S",
                            PerMinuteRate = 4.00m,
                            UnlockFee = 12.00m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kugoo Kirin M4",
                            PerMinuteRate = 5.50m,
                            UnlockFee = 18.00m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Велосипед складний Fold",
                            PerMinuteRate = 2.20m,
                            UnlockFee = 6.00m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ninebot F40",
                            PerMinuteRate = 4.80m,
                            UnlockFee = 16.00m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Електровелосипед Cargo",
                            PerMinuteRate = 5.00m,
                            UnlockFee = 20.00m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Segway P65",
                            PerMinuteRate = 6.00m,
                            UnlockFee = 25.00m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kugoo G-Booster",
                            PerMinuteRate = 5.80m,
                            UnlockFee = 22.00m
                        });
                });

            modelBuilder.Entity("CourseWork.Models.Rental", b =>
                {
                    b.HasOne("CourseWork.Models.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWork.Models.RentalPoint", "EndRentalPoint")
                        .WithMany("RentalsEndedHere")
                        .HasForeignKey("EndRentalPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CourseWork.Models.RentalPoint", "StartRentalPoint")
                        .WithMany("RentalsStartedHere")
                        .HasForeignKey("StartRentalPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CourseWork.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("EndRentalPoint");

                    b.Navigation("StartRentalPoint");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CourseWork.Models.Vehicle", b =>
                {
                    b.HasOne("CourseWork.Models.RentalPoint", "RentalPoint")
                        .WithMany("Vehicles")
                        .HasForeignKey("RentalPointId");

                    b.HasOne("CourseWork.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalPoint");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("CourseWork.Models.Client", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CourseWork.Models.RentalPoint", b =>
                {
                    b.Navigation("RentalsEndedHere");

                    b.Navigation("RentalsStartedHere");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CourseWork.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CourseWork.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
